version: '3.3'

services:
  traefik:
    image: traefik:2.3
    container_name: traefik
    restart: always
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/traefik.toml:/traefik.toml
      - ./config/traefik_dynamic.toml:/traefik_dynamic.toml
      - ./letsencrypt/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    labels:
      - traefik.http.routers.wordpress.rule=Host(`${HOST_BLOG}`)
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.routers.wordpress.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - proxy
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - internal
    labels:
      - traefik.enable=false

  portainer:
    image: portainer/portainer-ce:2.0.0
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks: 
      - proxy
    labels:
      # Frontend
      - "traefik.http.routers.frontend-portainer.rule=Host(`${HOST_PORTAINER`)"
      - "traefik.http.services.frontend-portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend-portainer.service=frontend-portainer"
      - "traefik.http.routers.frontend-portainer.tls.certresolver=lets-encrypt"

      # Edge
      - "traefik.enable=false"
      - "traefik.http.routers.edge.rule=Host(`${HOST_PORTAINER_EDGE}`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=lets-encrypt"

networks:
  proxy:
    external: true
  internal:
    external: false

volumes: 
  portainer_data: