[http.middlewares.simpleAuth.basicAuth]
  users = [
    # htpasswd -nb user password
    "user:password"
  ]

[http.routers.api]
  rule = "Host(`my-domain.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"